BEducat_v1/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("educat.urls",namespace='educat')),
]

educat/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'educat'
urlpatterns = [
    path('',views.home,name="home"),
    ########################################
    ############ensignant###################
    #######################################
    path("ensignant/",views.ensignant,name="ensignant_list"),
    path("ensignant/créer/",views.create_ensignant,name="ensignant_create"),
    path("ensignant/<int:ensignant_id>/", views.ensignant_consulter, name="ensignant_consulter"),
    path("ensignant/<int:ensignant_id>/modifier", views.ensignant_modifier, name="ensignant_modifier"),
    ########################################
    ############matiere###################
    #######################################
    path("matiere/",views.matiere,name="matiere_list"),
    path("matiere/créer/",views.create_matiere,name="matiere_create"), 
    ########################################
    ############Groupes###################
    #######################################
    path("groupes/",views.groupes,name="groupes_list"),
    path("groupes/créer/",views.create_groupes,name="groupes_create"),
    path("groupes/<int:groupe_id>/",views.groupe_consulter,name="groupe_consulter"),
     ########################################
    ############Etudient###################
    #######################################
    path("etudiant/",views.etudiant,name="etudiant_list"),
    path("etudiant/créer/",views.create_etudiant,name="etudiant_create"),
    ########################################
    ############auth###################
    #######################################
    path('login/',views.login_view,name="loginE"),
    path('change-password/', views.change_password_view, name='change_password'),
    path('logout/', views.logout_views, name='logout'),

    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

educat/models/student_models.py
from django.db import models

class Student(models.Model) :
    pass

educat/forms/auth_forms.py
from django import forms

class AuthForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Identifiant'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not username:
            raise forms.ValidationError("Le nom d'utilisateur ne peut pas être vide.")
        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("Le mot de passe ne peut pas être vide.")
        return password

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            if username == password:
                raise forms.ValidationError("Le nom d'utilisateur et le mot de passe ne peuvent pas être identiques.")
        
        return cleaned_data


class ChangerAuthForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nouveau mot de passe'}))
    conf_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmer le mot de passe'}))
    
    def clean_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        if not new_password:
            raise forms.ValidationError("Le mot de passe ne peut pas être vide.")
        return new_password

    def clean_conf_password(self):
        conf_password = self.cleaned_data.get('conf_password')
        if not conf_password:
            raise forms.ValidationError("La confirmation du mot de passe ne peut pas être vide.")
        return conf_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        conf_password = cleaned_data.get('conf_password')

        if new_password and conf_password:
            if new_password != conf_password:
                raise forms.ValidationError("Les mots de passe ne correspondent pas.")
        
        return cleaned_data

educat/forms/ensignant_forms.py
from django import forms
from educat.models import Enseignant

class CreerEnseignantForm(forms.ModelForm):
    class Meta:
        model = Enseignant
        fields = ['nom', 'prenom', 'role', 'cin', 'photo_profil']
        widgets = {
            'nom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton nom...'}),
            'prenom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton prénom...'}),
            'role': forms.Select(attrs={"class": "form-control"}),
            'cin': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton CIN...'}),
            'photo_profil': forms.ClearableFileInput(attrs={'class': 'custom-file-input'}),
        }

educat/forms/etudient_forms.py
from django import forms
from educat.models import Etudient,Groupe

class CreerInscriptionForm(forms.ModelForm):
    groupe = forms.ModelChoiceField(
        queryset=Groupe.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        empty_label="Sélectionner un groupe"
    )

    class Meta:
        model = Etudient
        fields = ['nom', 'prenom', 'cin', 'photo_profil', 'groupe']
        widgets = {
            'nom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton nom...'}),
            'prenom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton prénom...'}),
            'cin': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton CIN...'}),
            'photo_profil': forms.FileInput(attrs={"class": "form-control"}),
        }

educat/views/auth_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from educat.forms import AuthForm , ChangerAuthForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash
from educat.models import Enseignant
from django.contrib.auth.decorators import login_required


def login_view(request):
    if request.user.is_authenticated:
        return redirect("educat:home")
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                try:
                    enseignant = Enseignant.objects.get(user=user)
                    if enseignant.is_first_login:
                        return redirect('educat:change_password')
                except Enseignant.DoesNotExist:
                    pass 

                return redirect('educat:home')  
            else:
                form.add_error(None, "Identifiants invalides")
    else:
        form = AuthForm()

    context = {
        'form': form
    }
    return render(request, 'auth/login.html', context)

@login_required
def change_password_view(request):
    if request.method == 'POST':
        form = ChangerAuthForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            request.user.set_password(new_password)
            request.user.save()
            update_session_auth_hash(request, request.user)
            try:
                enseignant = Enseignant.objects.get(user=request.user)
                enseignant.update_first_login_status()  
            except Enseignant.DoesNotExist:
                pass  
            return redirect('educat:home')  
    else:
        form = ChangerAuthForm()

    return render(request, 'auth/change_password.html', {'form': form})

@login_required
def logout_views(request):
    logout(request)
    return HttpResponseRedirect('/login/')

educat/views/dashboard_views.py
from django.shortcuts import render
from educat.models import Enseignant ,Etudient
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.
@login_required
def home(request) :
    inscription_ce_mois = Etudient.get_inscription_ce_mois()
    inscription_total = Etudient.get_inscription_total()
    instance = get_object_or_404(Enseignant,user = request.user)
    print(instance)
    context = {
        "instance":instance,
        "inscription_ce_mois": inscription_ce_mois,
        "inscription_total" :inscription_total,
    }
    return render(request,"index.html",context)

educat/views/ensignant_views.py
from django.shortcuts import render , redirect
from django.urls import reverse
from educat.forms.ensignant_forms import CreerEnseignantForm
from educat.models import Enseignant ,Matiere
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

@login_required
def ensignant(request):
    qset = Enseignant.objects.all()
    context = {
        "qset" : qset
    }
    return render(request,"ensignant/ensignant_list.html",context)
@login_required
def create_ensignant(request):
    if request.method == "POST":
        form = CreerEnseignantForm(request.POST, request.FILES)
        if form.is_valid():
            nom = form.cleaned_data.get('nom')
            prenom = form.cleaned_data.get('prenom')
            cin = form.cleaned_data.get('cin')
            role = form.cleaned_data.get('role')
            photo_profil = form.cleaned_data.get('photo_profil')

            prof = Enseignant(
                nom=nom,
                prenom=prenom,
                cin=cin,
                role=role,
                photo_profil=photo_profil
            )

            obj, message = prof.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:ensignant_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerEnseignantForm()

    context = {
        "form": form
    }
    return render(request, "ensignant/ensignant_create.html", context)
@login_required
def ensignant_consulter(request,ensignant_id):
    instance = get_object_or_404(Enseignant,pk = ensignant_id)
    list_matiere = Matiere.get_groupes_matiere_enseignant(ensignant_id)
    if request.method == "POST":
        if request.POST.get('action') == "reset_password":
            obj,message = instance.reset_password()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:ensignant_list'))
            else:
                messages.error(request, message)
    context = {
        "instance" : instance,
        "list_matiere":list_matiere
    }
    return render(request, "ensignant/ensignant_consulter.html", context)

@login_required
def ensignant_modifier(request, ensignant_id):
    instance = get_object_or_404(Enseignant, pk=ensignant_id)

    if request.method == "POST":
        form = CreerEnseignantForm(request.POST, request.FILES, instance=instance)
        
        if form.is_valid():
            nom = form.cleaned_data['nom']
            prenom = form.cleaned_data['prenom']
            cin = form.cleaned_data['cin']
            role = form.cleaned_data['role']
            photo_profil = form.cleaned_data['photo_profil']
            instance.nom = nom
            instance.prenom = prenom
            instance.cin = cin
            instance.role = role
            instance.photo_profil = photo_profil
            obj, message =instance.c_update()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:ensignant_list'))
            else:
                messages.error(request, message)
            context = {
                'form': form,
                'message': "Enseignant bien mis à jour"
            }
            return render(request, 'ensignant/ensignant_modifier.html', context)
    else:
        form = CreerEnseignantForm(instance=instance)

    context = {
        'form': form
    }
    return render(request, 'ensignant/ensignant_modifier.html', context)
     

educat/views/etudient_views.py
from django.shortcuts import render ,redirect 
from django.urls import reverse
from educat.models import Etudient
from educat.forms import CreerInscriptionForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def create_etudiant(request):
    if request.method == "POST":
        form = CreerInscriptionForm(request.POST, request.FILES)
        if form.is_valid():
            nom = form.cleaned_data.get('nom')
            prenom = form.cleaned_data.get('prenom')
            cin = form.cleaned_data.get('cin')
            photo_profil = form.cleaned_data.get('photo_profil')
            groupe = form.cleaned_data.get('groupe')

            etudient = Etudient(
                nom=nom,
                prenom=prenom,
                cin=cin,
                photo_profil=photo_profil,
                groupe=groupe,
            )

            obj, message = etudient.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:etudiant_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerInscriptionForm()

    context = {
        "form": form
    }
    return render(request, "etudient/etudient_create.html", context)

@login_required
def etudiant(request):
    qset = Etudient.objects.all()
    context = {
        "qset" : qset
    }
    return render(request,"etudient/etudient_list.html",context)

educat/views/groupes_views.py
from django.shortcuts import render ,redirect 
from django.urls import reverse
from educat.models import Groupe ,Etudient
from educat.forms import CreerGroupestForm
from django.forms import formset_factory
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


@login_required
def groupes(request):
    
    qset = Groupe.objects.all()
    context = {
        "qset" : qset,
    }
    return render(request,"groupes/groupes_list.html",context)
@login_required
def create_groupes(request):
    if request.method == "POST":
        form = CreerGroupestForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            max_inscription = form.cleaned_data.get('max_inscription')
            groupe = Groupe(
                name=name,
                description=description,
                max_inscription=max_inscription,
            )

            obj, message = groupe.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:groupes_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerGroupestForm()
        
    context = {
        "form" : form
    }
    return render(request,"groupes/groupes_create.html",context)

def groupe_consulter(request,groupe_id):
    instance = get_object_or_404(Groupe,pk = groupe_id)
    context = {
        "instance" : instance
    }
    return render(request,"groupes/groupe_consulter.html",context)
    

educat/views/matiere_views.py
from django.shortcuts import render ,redirect 
from django.urls import reverse
from educat.models import Matiere
from educat.forms import CreerMatiereForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required
def matiere(request):
    qset = Matiere.objects.all()
    context= {
        "qset":qset,
    }
    return render(request , "matiere/matiere_list.html",context)

@login_required
def create_matiere(request):
    if request.method == "POST":
        form = CreerMatiereForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            code = form.cleaned_data.get('code')
            niveau = form.cleaned_data.get('niveau')
            volume_horaire = form.cleaned_data.get('volume_horaire')
            enseignant = form.cleaned_data.get('enseignant')

            matiere = Matiere(
                title=title,
                code=code,
                niveau=niveau,
                volume_horaire=volume_horaire,
                enseignant=enseignant
            )

            obj, message = matiere.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:matiere_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerMatiereForm()

    context = {
        "form": form
    }
    return render(request, "matiere/matiere_create.html", context)

educat/templates/parts/footer.html
      <!--begin::Footer-->
      <footer class="app-footer">
        <!--begin::To the end-->
        <div class="float-end d-none d-sm-inline">Anything you want</div>
        <!--end::To the end-->
        <!--begin::Copyright-->
        <strong>
          Copyright &copy; 2014-2024&nbsp;
          <a href="https://adminlte.io" class="text-decoration-none">AdminLTE.io</a>.
        </strong>
        All rights reserved.
        <!--end::Copyright-->
      </footer>
      <!--end::Footer-->

educat/templates/parts/head.html
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>AdminLTE v4 | Dashboard</title>
    <!--begin::Primary Meta Tags-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="title" content="AdminLTE v4 | Dashboard" />
    <meta name="author" content="ColorlibHQ" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta
      name="description"
      content="AdminLTE is a Free Bootstrap 5 Admin Dashboard, 30 example pages using Vanilla JS."
    />
    <meta
      name="keywords"
      content="bootstrap 5, bootstrap, bootstrap 5 admin dashboard, bootstrap 5 dashboard, bootstrap 5 charts, bootstrap 5 calendar, bootstrap 5 datepicker, bootstrap 5 tables, bootstrap 5 datatable, vanilla js datatable, colorlibhq, colorlibhq dashboard, colorlibhq admin dashboard"
    />
    <!--end::Primary Meta Tags-->
    <!--begin::Fonts-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fontsource/source-sans-3@5.0.12/index.css"
      integrity="sha256-tXJfXfp6Ewt1ilPzLDtQnJV4hclT9XuaZUKyUvmyr+Q="
      crossorigin="anonymous"
    />
    <!--end::Fonts-->
    <!--begin::Third Party Plugin(OverlayScrollbars)-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.10.1/styles/overlayscrollbars.min.css"
      integrity="sha256-tZHrRjVqNSRyWg2wbppGnT833E/Ys0DHWGwT04GiqQg="
      crossorigin="anonymous"
    />
    <!--end::Third Party Plugin(OverlayScrollbars)-->
    <!--begin::Third Party Plugin(Bootstrap Icons)-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
      integrity="sha256-9kPW/n5nn53j4WMRYAxe9c1rCY96Oogo/MKSVdKzPmI="
      crossorigin="anonymous"
    />
    <!--end::Third Party Plugin(Bootstrap Icons)-->
    <!--begin::Required Plugin(AdminLTE)-->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.css' %}" />
    <!--end::Required Plugin(AdminLTE)-->
    <!-- apexcharts -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/apexcharts@3.37.1/dist/apexcharts.css"
      integrity="sha256-4MX+61mt9NVvvuPjUWdUdyfZfxSB1/Rf9WtqRHgG5S0="
      crossorigin="anonymous"
    />
    <!-- jsvectormap -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/jsvectormap@1.5.3/dist/css/jsvectormap.min.css"
      integrity="sha256-+uGLJmmTKOqBr+2E6KDYs/NRsHxSkONXFHUL0fy2O/4="
      crossorigin="anonymous"
    />
  </head>

educat/templates/parts/seidbar.html
{% load static %}
 <!--begin::Sidebar-->
 <aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark">
    <!--begin::Sidebar Brand-->
    <div class="sidebar-brand">
      <!--begin::Brand Link-->
      <a href="./index.html" class="brand-link">
        <!--begin::Brand Image-->
        <img
          src="{% static 'dist/assets/img/AdminLTELogo.png' %}"
          alt="AdminLTE Logo"
          class="brand-image opacity-75 shadow"
        />
        <!--end::Brand Image-->
        <!--begin::Brand Text-->
        <span class="brand-text fw-light">AdminLTE 4</span>
        <!--end::Brand Text-->
      </a>
      <!--end::Brand Link-->
    </div>
    <!--end::Sidebar Brand-->
    <!--begin::Sidebar Wrapper-->
    <div class="sidebar-wrapper">
      <nav class="mt-2">
        <!--begin::Sidebar Menu-->
        <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">
          <!-- Menu Enseignant -->
          <li class="nav-item menu-{% if request.path == '/ensignant/' or request.path == '/ensignant/créer/' %}open{% endif %}">
            <a href="#" class="nav-link {% if request.path == '/ensignant/' or request.path == '/ensignant/créer/' %}active{% endif %}">
              <i class="fa-solid fa-user-tie"></i>           
                 <p>
                Enseignant
                <i class="nav-arrow bi bi-chevron-right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'educat:ensignant_list' %}" class="nav-link {% if request.path == '/ensignant/' %}active{% endif %}">
                  <i class="fa-solid fa-list"></i>
                  <p>List enseignant</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'educat:ensignant_create' %}" class="nav-link {% if request.path == '/ensignant/créer/' %}active{% endif %}">
                  <i class="fa-solid fa-plus"></i>
                  <p>Ajouter enseignant</p>
                </a>
              </li>
            </ul>
          </li>
        
          <!-- Menu Matière -->
          <li class="nav-item menu-{% if request.path == '/matiere/' or request.path == '/matiere/créer/' %}open{% endif %}">
            <a href="#" class="nav-link {% if request.path == '/matiere/' or request.path == '/matiere/créer/' %}active{% endif %}">
              <i class="bi bi-book-fill"></i> <!-- Remplacer l'icône si nécessaire -->
              <p>
                Matière
                <i class="nav-arrow bi bi-chevron-right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'educat:matiere_list' %}" class="nav-link {% if request.path == '/matiere/' %}active{% endif %}">
                  <i class="fa-solid fa-list"></i>
                  <p>List matière</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'educat:matiere_create' %}" class="nav-link {% if request.path == '/matiere/créer/' %}active{% endif %}">
                  <i class="fa-solid fa-plus"></i>
                  <p>Ajouter matière</p>
                </a>
              </li>
            </ul>
          </li>
            <!-- Menu Groupes -->
            <li class="nav-item menu-{% if request.path == '/groupes/' or request.path == '/groupes/créer/' or request.path == 'etudient/créer/' %}open{% endif %}">
              <a href="#" class="nav-link {% if request.path == '/groupes/' or request.path == '/groupes/créer/' or request.path == 'etudient/créer/' %}active{% endif %}">
                <i class="fa-solid fa-users"></i> <!-- Icône d'un groupe de personnes -->
                <p>
                  Groupes
                  <i class="nav-arrow bi bi-chevron-right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'educat:groupes_list' %}" class="nav-link {% if request.path == '/groupes/' %}active{% endif %}">
                    <i class="fa-solid fa-list"></i>
                    <p>List Groupe</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'educat:groupes_create' %}" class="nav-link {% if request.path == '/groupes/créer/' %}active{% endif %}">
                    <i class="fa-solid fa-plus"></i>
                    <p>Ajouter Groupes</p>
                  </a>
              </ul>
            </li>
            <!-- Menu etudient -->
            <li class="nav-item menu-{% if request.path == '/etudiant/' or request.path == '/etudiant/créer/' %}open{% endif %}">
              <a href="#" class="nav-link {% if request.path == '/etudiant/' or request.path == '/etudiant/créer/' %}active{% endif %}">
                <i class="fa-solid fa-users-line"></i>
                <p>
                  Etudiant
                  <i class="nav-arrow bi bi-chevron-right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'educat:etudiant_list' %}" class="nav-link {% if request.path == '/etudiant/' %}active{% endif %}">
                    <i class="fa-solid fa-list"></i>
                    <p>List etudiant</p>
                  </a>
                </li>
               
                <li class="nav-item">
                  <a href="{% url 'educat:etudiant_create' %}" class="nav-link {% if request.path == '/etudiant/créer/' %}active{% endif %}">
                    <i class="fa-solid fa-plus"></i>
                    <p>Ajouter inscription</p>
                  </a>
                </li>
              </ul>
            </li>
        </ul>
        
        <!--end::Sidebar Menu-->
      </nav>
    </div>
    <!--end::Sidebar Wrapper-->
  </aside>
  <!--end::Sidebar-->