BEducat_v1/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("educat.urls",namespace='educat')),
]

educat/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'educat'
urlpatterns = [
    path('',views.home,name="home"),
    ########################################
    ############ensignant###################
    #######################################
    path("ensignant/",views.ensignant,name="ensignant_list"),
    path("ensignant/créer/",views.create_ensignant,name="ensignant_create"),
    path("ensignant/<int:ensignant_id>/", views.ensignant_consulter, name="ensignant_consulter"),
    path("ensignant/<int:ensignant_id>/modifier", views.ensignant_modifier, name="ensignant_modifier"),
    ########################################
    ############matiere###################
    #######################################
    path("matiere/",views.matiere,name="matiere_list"),
    path("matiere/créer/",views.create_matiere,name="matiere_create"), 
    ########################################
    ############Groupes###################
    #######################################
    path("groupes/",views.groupes,name="groupes_list"),
    path("groupes/créer/",views.create_groupes,name="groupes_create"),
    path("groupes/<int:groupe_id>/",views.groupe_consulter,name="groupe_consulter"),
     ########################################
    ############Etudient###################
    #######################################
    path("etudiant/",views.etudiant,name="etudiant_list"),
    path("etudiant/créer/",views.create_etudiant,name="etudiant_create"),
    ########################################
    ############auth###################
    #######################################
    path('login/',views.login_view,name="loginE"),
    path('change-password/', views.change_password_view, name='change_password'),
    path('logout/', views.logout_views, name='logout'),

    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

educat/models/student_models.py
from django.db import models

class Student(models.Model) :
    pass

educat/forms/auth_forms.py
from django import forms

class AuthForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Identifiant'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not username:
            raise forms.ValidationError("Le nom d'utilisateur ne peut pas être vide.")
        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("Le mot de passe ne peut pas être vide.")
        return password

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            if username == password:
                raise forms.ValidationError("Le nom d'utilisateur et le mot de passe ne peuvent pas être identiques.")
        
        return cleaned_data


class ChangerAuthForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nouveau mot de passe'}))
    conf_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmer le mot de passe'}))
    
    def clean_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        if not new_password:
            raise forms.ValidationError("Le mot de passe ne peut pas être vide.")
        return new_password

    def clean_conf_password(self):
        conf_password = self.cleaned_data.get('conf_password')
        if not conf_password:
            raise forms.ValidationError("La confirmation du mot de passe ne peut pas être vide.")
        return conf_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        conf_password = cleaned_data.get('conf_password')

        if new_password and conf_password:
            if new_password != conf_password:
                raise forms.ValidationError("Les mots de passe ne correspondent pas.")
        
        return cleaned_data

educat/forms/ensignant_forms.py
from django import forms
from educat.models import Enseignant

class CreerEnseignantForm(forms.ModelForm):
    class Meta:
        model = Enseignant
        fields = ['nom', 'prenom', 'role', 'cin', 'photo_profil']
        widgets = {
            'nom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton nom...'}),
            'prenom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton prénom...'}),
            'role': forms.Select(attrs={"class": "form-control"}),
            'cin': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton CIN...'}),
            'photo_profil': forms.ClearableFileInput(attrs={'class': 'custom-file-input'}),
        }

educat/forms/etudient_forms.py
from django import forms
from educat.models import Etudient,Groupe

class CreerInscriptionForm(forms.ModelForm):
    groupe = forms.ModelChoiceField(
        queryset=Groupe.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        empty_label="Sélectionner un groupe"
    )

    class Meta:
        model = Etudient
        fields = ['nom', 'prenom', 'cin', 'photo_profil', 'groupe']
        widgets = {
            'nom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton nom...'}),
            'prenom': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton prénom...'}),
            'cin': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Entrer ton CIN...'}),
            'photo_profil': forms.FileInput(attrs={"class": "form-control"}),
        }

educat/views/auth_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from educat.forms import AuthForm , ChangerAuthForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash
from educat.models import Enseignant
from django.contrib.auth.decorators import login_required


def login_view(request):
    if request.user.is_authenticated:
        return redirect("educat:home")
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                try:
                    enseignant = Enseignant.objects.get(user=user)
                    if enseignant.is_first_login:
                        return redirect('educat:change_password')
                except Enseignant.DoesNotExist:
                    pass 

                return redirect('educat:home')  
            else:
                form.add_error(None, "Identifiants invalides")
    else:
        form = AuthForm()

    context = {
        'form': form
    }
    return render(request, 'auth/login.html', context)

@login_required
def change_password_view(request):
    if request.method == 'POST':
        form = ChangerAuthForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            request.user.set_password(new_password)
            request.user.save()
            update_session_auth_hash(request, request.user)
            try:
                enseignant = Enseignant.objects.get(user=request.user)
                enseignant.update_first_login_status()  
            except Enseignant.DoesNotExist:
                pass  
            return redirect('educat:home')  
    else:
        form = ChangerAuthForm()

    return render(request, 'auth/change_password.html', {'form': form})

@login_required
def logout_views(request):
    logout(request)
    return HttpResponseRedirect('/login/')

educat/views/dashboard_views.py
from django.shortcuts import render
from educat.models import Enseignant ,Etudient
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.
@login_required
def home(request) :
    inscription_ce_mois = Etudient.get_inscription_ce_mois()
    inscription_total = Etudient.get_inscription_total()
    instance = get_object_or_404(Enseignant,user = request.user)
    print(instance)
    context = {
        "instance":instance,
        "inscription_ce_mois": inscription_ce_mois,
        "inscription_total" :inscription_total,
    }
    return render(request,"index.html",context)

educat/views/ensignant_views.py
from django.shortcuts import render , redirect
from django.urls import reverse
from educat.forms.ensignant_forms import CreerEnseignantForm
from educat.models import Enseignant ,Matiere
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

@login_required
def ensignant(request):
    qset = Enseignant.objects.all()
    context = {
        "qset" : qset
    }
    return render(request,"ensignant/ensignant_list.html",context)
@login_required
def create_ensignant(request):
    if request.method == "POST":
        form = CreerEnseignantForm(request.POST, request.FILES)
        if form.is_valid():
            nom = form.cleaned_data.get('nom')
            prenom = form.cleaned_data.get('prenom')
            cin = form.cleaned_data.get('cin')
            role = form.cleaned_data.get('role')
            photo_profil = form.cleaned_data.get('photo_profil')

            prof = Enseignant(
                nom=nom,
                prenom=prenom,
                cin=cin,
                role=role,
                photo_profil=photo_profil
            )

            obj, message = prof.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:ensignant_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerEnseignantForm()

    context = {
        "form": form
    }
    return render(request, "ensignant/ensignant_create.html", context)
@login_required
def ensignant_consulter(request,ensignant_id):
    instance = get_object_or_404(Enseignant,pk = ensignant_id)
    list_matiere = Matiere.get_groupes_matiere_enseignant(ensignant_id)
    if request.method == "POST":
        if request.POST.get('action') == "reset_password":
            obj,message = instance.reset_password()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:ensignant_list'))
            else:
                messages.error(request, message)
    context = {
        "instance" : instance,
        "list_matiere":list_matiere
    }
    return render(request, "ensignant/ensignant_consulter.html", context)

@login_required
def ensignant_modifier(request, ensignant_id):
    instance = get_object_or_404(Enseignant, pk=ensignant_id)

    if request.method == "POST":
        form = CreerEnseignantForm(request.POST, request.FILES, instance=instance)
        
        if form.is_valid():
            nom = form.cleaned_data['nom']
            prenom = form.cleaned_data['prenom']
            cin = form.cleaned_data['cin']
            role = form.cleaned_data['role']
            photo_profil = form.cleaned_data['photo_profil']
            instance.nom = nom
            instance.prenom = prenom
            instance.cin = cin
            instance.role = role
            instance.photo_profil = photo_profil
            obj, message =instance.c_update()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:ensignant_list'))
            else:
                messages.error(request, message)
            context = {
                'form': form,
                'message': "Enseignant bien mis à jour"
            }
            return render(request, 'ensignant/ensignant_modifier.html', context)
    else:
        form = CreerEnseignantForm(instance=instance)

    context = {
        'form': form
    }
    return render(request, 'ensignant/ensignant_modifier.html', context)
     

educat/views/etudient_views.py
from django.shortcuts import render ,redirect 
from django.urls import reverse
from educat.models import Etudient
from educat.forms import CreerInscriptionForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def create_etudiant(request):
    if request.method == "POST":
        form = CreerInscriptionForm(request.POST, request.FILES)
        if form.is_valid():
            nom = form.cleaned_data.get('nom')
            prenom = form.cleaned_data.get('prenom')
            cin = form.cleaned_data.get('cin')
            photo_profil = form.cleaned_data.get('photo_profil')
            groupe = form.cleaned_data.get('groupe')

            etudient = Etudient(
                nom=nom,
                prenom=prenom,
                cin=cin,
                photo_profil=photo_profil,
                groupe=groupe,
            )

            obj, message = etudient.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:etudiant_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerInscriptionForm()

    context = {
        "form": form
    }
    return render(request, "etudient/etudient_create.html", context)

@login_required
def etudiant(request):
    qset = Etudient.objects.all()
    context = {
        "qset" : qset
    }
    return render(request,"etudient/etudient_list.html",context)

educat/views/groupes_views.py
from django.shortcuts import render ,redirect 
from django.urls import reverse
from educat.models import Groupe ,Etudient
from educat.forms import CreerGroupestForm
from django.forms import formset_factory
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


@login_required
def groupes(request):
    
    qset = Groupe.objects.all()
    context = {
        "qset" : qset,
    }
    return render(request,"groupes/groupes_list.html",context)
@login_required
def create_groupes(request):
    if request.method == "POST":
        form = CreerGroupestForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            max_inscription = form.cleaned_data.get('max_inscription')
            groupe = Groupe(
                name=name,
                description=description,
                max_inscription=max_inscription,
            )

            obj, message = groupe.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:groupes_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerGroupestForm()
        
    context = {
        "form" : form
    }
    return render(request,"groupes/groupes_create.html",context)

def groupe_consulter(request,groupe_id):
    instance = get_object_or_404(Groupe,pk = groupe_id)
    context = {
        "instance" : instance
    }
    return render(request,"groupes/groupe_consulter.html",context)
    

educat/views/matiere_views.py
from django.shortcuts import render ,redirect 
from django.urls import reverse
from educat.models import Matiere
from educat.forms import CreerMatiereForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required
def matiere(request):
    qset = Matiere.objects.all()
    context= {
        "qset":qset,
    }
    return render(request , "matiere/matiere_list.html",context)

@login_required
def create_matiere(request):
    if request.method == "POST":
        form = CreerMatiereForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            code = form.cleaned_data.get('code')
            niveau = form.cleaned_data.get('niveau')
            volume_horaire = form.cleaned_data.get('volume_horaire')
            enseignant = form.cleaned_data.get('enseignant')

            matiere = Matiere(
                title=title,
                code=code,
                niveau=niveau,
                volume_horaire=volume_horaire,
                enseignant=enseignant
            )

            obj, message = matiere.c_create()
            if obj:
                messages.success(request, message)
                return redirect(reverse('educat:matiere_list'))
            else:
                messages.error(request, message)

    else:
        form = CreerMatiereForm()

    context = {
        "form": form
    }
    return render(request, "matiere/matiere_create.html", context)

educat/templates/ensignant/ensignant_consulter.html
{% extends base_template %}

{% block content %}
<div class="container-fluid card">
    <div class="card card-primary card-outline mb-2 m-3">
        <div class="card-header">
            <div class="card-title" style="display: flex; justify-content: space-around;width: 100%;">
                <div class="left-part" style="display: flex; justify-content: space-around;width: 30%;">

                    <div>
                        <p>Nom </p>
                        <p>Prenom</p>
                        <p>Cin</p>
                    </div>
                    <div>
                        <p>:</p>
                        <p>:</p>
                        <p>:</p>
                    </div>
                    <div>
                        <p>{{ instance.nom }} </p>
                        <p>{{ instance.prenom }}</p>
                        <p>{{ instance.cin }}</p>
                    </div>

                </div>
                <div class="center-part">
                    <p>-</p>
                    <p>-</p>
                    <p>-</p>
                </div>
                <div class="right-part" style="display: flex; justify-content: space-around; width: 50%;">
                    <div>
                        <p>Identifiant</p>
                        <p>Mot de passe</p>
                        {% if not instance.is_first_login %}
                        <p>Reinitialiser mot de passe </p>
                        {% endif %}
                    </div>
                    <div>
                        <p>:</p>
                        <p>:</p>
                        {% if not instance.is_first_login %}
                        <p>:</p>
                        {% endif %}
                    </div>
                    <div>
                        <p>{{ instance.user.username }}</p>
                        
                        {% if instance.is_first_login %}
                            <p>Mot de passe temporaire : <b>{{ instance.temp_password }}</b></p>
                        {% else %}
                            <p>Mot de passe défini</p>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="reset_password">
                                <a href="#" onclick="this.closest('form').submit();">Cliquez ici pour réinitialiser votre mot de passe...</a>
                            </form>
                            
                        {% endif %}
                    </div>
                </div>
                
            </div>
        </div>
        
    </div> 
    <div class="card card-info card-outline mb-4 m-3">
        <div class="card-header">
            <div class="card-title text-info">Liste des matières</div>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Matière</th>
                    <th>Code</th>
                    <th>Niveau</th>
                    <th>Groupes</th>
                  </tr>
                </thead>
                <tbody>
                    {% for qset in list_matiere.matiere %}
                        <tr>
                            <td>{{ qset.title }}</td>
                            <td>{{ qset.code }}</td>
                            <td>{{ qset.niveau }}</td>
                            <td>
                                {% for groupe in list_matiere.groupes %}
                                <a href="{% url 'educat:groupe_consulter' groupe.id %}">{{ groupe }}</a>{% if not forloop.last %} / {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="4">Aucune matière disponible</td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
   
    </div> 
</div>
{% endblock content %}

educat/templates/ensignant/ensignant_create.html
{% extends base_template%}

{% block content %}
<div class="container-fluid card">
    <div class="card card-primary card-outline mb-4 m-3">
        <div class="card-header">
            <div class="card-title">Quick Example</div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label">{{ form.nom.label }}</label>
                    {{ form.nom }}
                    {% if form.nom.errors %}
                        <div class="text-danger">
                            {% for error in form.nom.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.prenom.label }}</label>
                    {{ form.prenom }}
                    {% if form.prenom.errors %}
                        <div class="text-danger">
                            {% for error in form.prenom.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.role.label }}</label>
                    {{ form.role }}
                    {% if form.role.errors %}
                        <div class="text-danger">
                            {% for error in form.role.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.cin.label }}</label>
                    {{ form.cin }}
                    {% if form.cin.errors %}
                        <div class="text-danger">
                            {% for error in form.cin.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.photo_profil.label }}</label>
                    {{ form.photo_profil }}
                    {% if form.photo_profil.errors %}
                        <div class="text-danger">
                            {% for error in form.photo_profil.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        
        </form>
    </div> 
</div>
{% endblock content %}

educat/templates/ensignant/ensignant_list.html
{% extends base_template %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <div class="p-3">
        
            <div class="card mb-4">
                <div class="card-header"><h3 class="card-title">Bordered Table</h3></div>
                <!-- /.card-header -->
                <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th style="text-align: center;">Nom</th>
                        <th style="text-align: center;">Prenom</th>
                        <th style="text-align: center;">action</th>
                    </tr>
                    </thead>
                    <tbody>
                        
                        {% for prof in qset %}
                        <tr class="align-middle" onclick="window.location='{{prof.id}}';" style="cursor: pointer;">
                            <td style="text-align: center;">{{prof.id}}</td>
                            <td style="text-align: center;">{{prof.nom}}</td>
                            <td style="text-align: center;">{{prof.prenom}}</td>
                            <td style="text-align: center;">
                                <div class="btn-group">
                                    <button type="button" onclick="event.stopPropagation();" class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        Options
                                    </button>
                                    <ul class="dropdown-menu" >
                                        <li><a class="dropdown-item" href="{% url 'educat:ensignant_modifier' prof.id %}">Modifier</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    
                    

                    </tbody>
                </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-end">
                    <li class="page-item"><a class="page-link" href="#">«</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
                </div>
            </div>
    </div>   
{% endblock content %}
    

educat/templates/ensignant/ensignant_modifier.html
{% extends base_template%}

{% block content %}
<div class="container-fluid card">
    <div class="card card-primary card-outline mb-4 m-3">
        <div class="card-header">
            <div class="card-title">Quick Example</div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label">{{ form.nom.label }}</label>
                    {{ form.nom }}
                    {% if form.nom.errors %}
                        <div class="text-danger">
                            {% for error in form.nom.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.prenom.label }}</label>
                    {{ form.prenom }}
                    {% if form.prenom.errors %}
                        <div class="text-danger">
                            {% for error in form.prenom.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.role.label }}</label>
                    {{ form.role }}
                    {% if form.role.errors %}
                        <div class="text-danger">
                            {% for error in form.role.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.cin.label }}</label>
                    {{ form.cin }}
                    {% if form.cin.errors %}
                        <div class="text-danger">
                            {% for error in form.cin.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label class="form-label">{{ form.photo_profil.label }}</label>
                    {{ form.photo_profil }}
                    {% if form.photo_profil.errors %}
                        <div class="text-danger">
                            {% for error in form.photo_profil.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        
        </form>
    </div> 
</div>
{% endblock content %}